# Generated by Django 5.2 on 2025-05-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
