# Generated by Django 5.2 on 2025-05-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_booking_created_at_alter_booking_depart_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
