# Generated by Django 5.2 on 2025-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(),
        ),
    ]
