# Generated by Django 5.2 on 2025-05-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_booking_depart_date_alter_booking_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
