# Generated by Django 4.2.23 on 2025-07-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
